name: 'My Action'
description: 'Custom GitHub Action with log analysis'
author: 'Your Name'

inputs:
  message:
    description: 'Message to print'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Print step summary
      run: |
        cd ${{ inputs.repo_path }}
        npm list --depth=10
      shell: bash